version: '3.8'

services:
  locar-api:
    container_name: locar-api
    image: locar-api:latest
    build:
      context: .
    ports:
      - "${SERVER_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - locadb
    networks:
      - locar-network

  locadb:
    image: postgres:latest
    container_name: locadb
    restart: unless-stopped
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - locadb_data:/var/lib/postgresql/data
    networks:
      - locar-network

networks:
  locar-network:
    driver: bridge

volumes:
  locadb_data:
    driver: local