server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    messages:
      encoding: ISO-8859-1

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, metrics, openapi, swagger-ui


springdoc:
  show-actuator: false
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs